PATH_PREFIX = 'LOCATE_YOUR_PROJECT_FULL_PATH_HERE'
LOG_PREFIX = f'{PATH_PREFIX}/logs'

# Status Code
OK = 200
UNAUTHORIZED = 401

# Authentication
SECRET = 'SECRET_PLACEHOLDER'
ALGORITHM = 'ALGORITHM_PLACEHOLDER'
AUTH_BODY = 'AUTH_BODY_PLACEHOLDER'
