PATH_PREFIX = '/app'
LOG_PREFIX = f'{PATH_PREFIX}/logs'

# Status Code
OK = 200
UNAUTHORIZED = 401

# Authentication
REQUIRED_AUTH = False
SECRET = 'SECRET_PLACEHOLDER'
AUTH_BODY = 'AUTH_BODY_PLACEHOLDER'
ALGORITHM = 'HS256'
